### ISSUE TITLE
Slash commands support

### ISSUE THREAD

**Issue by the94air** [the94air/monitord#1]
This is a Discord bot for monitoring live websites. Currently Discord.js v12 is used which lack the support for slash commands.
The contribution needed is to upgrade to v14 (this feature rely on this second feature #2)  and then implement slash commands support over the existing functional implementation. Let me know if you need any help!
I will add a link to the contributors page on README once the PR is accepted and merged! Thank you!

**Comment by code913** [comment]
hi

**Comment by the94air** [comment]
hello

**Comment by oof2win2** [comment]
Can I claim this?

**Comment by the94air** [comment]
Thanks for the contribution, go ahead! 👍 would be great if we can merge #2 first.

**Comment by the94air** [comment]
@oof2win2 just want to check if you still want to contribute on this issue. As #4 will be merged in couple of hours! 👍

**Comment by oof2win2** [comment]
Yes. Was waiting for #4 to be merged, as djs@12 does not support slash commands. Needed 13+ for me to be able to start.

**Comment by the94air** [comment]
Yup, just checking for the contribution intention! that's all! :) Perfect!

**Comment by the94air** [comment]
@oof2win2 alright, so everything seem ready, make sure to use the `main` branch and not the `stable` branch :+1:
