### ISSUE TITLE
Upgrade to Discord.js v14

### ISSUE THREAD

**Issue by the94air** [the94air/monitord#2]
Currently this project is running with discord.js v12. The required contribution is to upgrade to the latest version of discord.js v14 while focusing on the functionality of each command. If you want to look into implementing the other slash commands feature, make sure to look into the previous issue #1. Let me know if you need any help!
I will add a link to the contributors page on README once the PR is accepted and merged! Thank you!

**Comment by oof2win2** [comment]
Can I claim this one please?

**Comment by camdenorrb** [comment]
@oof2win2 Too late, about to push it

**Comment by camdenorrb** [comment]
PR #4 resolves it

**Comment by the94air** [comment]
Great work, I'll look into it later 👍 Looks like this is already in the work @oof2win2 sorry! ❤️
